server: 
   port: 8080
eureka: 
  client:
    service-url: 
      default-zone: http://localhost:8761/eureka/
spring:
   application:
       name: APIGatewayService
   cloud: 
      gateway:
          routes: 
            - id: HSBAdminLocationModule
              uri: http://localhost:8081/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBAdminDestinationModule
              uri: http://localhost:8082/
              predicates:
              - Path=/api/v1/**
            - id: HSBAdminSpotModule
              uri: http://localhost:8083/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBAdminRoomTypeModule
              uri: http://localhost:8084/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBAdminRoomsModule
              uri: http://localhost:8085/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBUserLocationModule
              uri: http://localhost:8086/
              predicates:
              - Path=/api/loc/**
            - id: HSBUserDestinationModule
              uri: http://localhost:8087/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBUserSpotModule
              uri: http://localhost:8088/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBUserRoomTypeModule
              uri: http://localhost:8089/
              predicates:
              - Path=/api/v1/get/**
            - id: HSBUserLocationModule
              uri: http://localhost:8090/
              predicates:
              - Path=/api/v1/get/**
            - id: JWTUtilityModule
              uri: http://localhost:8095/
              predicates:
              - Path=/api/jwt/**